name: ges 
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.10
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - -e submodules/diff-gaussian-rasterization/
    - -e submodules/simple-knn/
    - matplotlib 
    - pandas 
    - imageio 
    - trimesh 
    - einops 
    - opencv-python 
    - wandb 
